server:
  port: 8084

spring:
  application:
    name: quiz-service
  datasource:
    url: jdbc:postgresql://ep-rapid-sound-a1kaofxv-pooler.ap-southeast-1.aws.neon.tech/quiz_db?sslmode=require&channel_binding=require
    username: neondb_owner
    password: npg_mNdp0bjfCsX9
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
